### ISSUE TITLE
Save all in an alternate location

### ISSUE THREAD

**Issue by TheCJGCJG** [ScreenShottr/ScreenShottr-Java#12]
The ability to save a copy of your ScreenShots in another location aswell as uploaded. Configurable of course.

**Comment by robingall2910** [comment]
Ooh, like for linux/windows, it can be a hidden folder as in .screenshottr or My Screenshottr (Pictures, uploads, etc)

**Comment by TheCJGCJG** [comment]
2+ years since last acitivity. Closing
