### ISSUE TITLE
Mac OS Retina, uses Non-Native screen resolution

### ISSUE THREAD

**Issue by TheCJGCJG** [ScreenShottr/ScreenShottr-Java#6]
On a Mac with Retina display, the ScreenShottr-Java application takes in a non-native resolution
ScreenShottr-Java
![65eb4988b4f8ec0ad1139a4144a96c25](https://cloud.githubusercontent.com/assets/1349339/4515735/77f5bc98-4bcf-11e4-9fde-2e1d14d51097.png)

Mac OS Native
![187452899361f5cf80bb060a3d58aeba](https://cloud.githubusercontent.com/assets/1349339/4515736/7dd76828-4bcf-11e4-93ad-5968b1ea4807.png)

**Comment by JeromSar** [comment]
Try again with the latest build I sent you. @TheCJGCJG :)

**Comment by TheCJGCJG** [comment]
The latest build has not fixed this.
