### ISSUE TITLE
Landing page & Share Options

### ISSUE THREAD

**Issue by TheCJGCJG** [ScreenShottr/ScreenShottr-Java#7]
With the ScreenShottr-Web repo, you can add have a URL in the format of `https://<url>/v/landing/<key>/<img>` OR `https://<url>/v/landing/<img>` This is just adding the /landing/ after the /v/ and before the key, for an encrypted image and before the image for the unencrypted images.

This provides an image that looks like [This](https://www.screenshottr.us/v/landing/bf3bc9a33ddd132ade204b24301b7558/14324a3cd3ffe53a8efdb900a5df474b.jpg) - Note that this page will be changed, and branding changed eventually.

This will produce a landing page, which will have Share Options, and could be a config option in the way that you can turn on/off this landing page.
This shouldnt be too hard as ScreenShottr returns the following JSON

``` json
{
   "pravius":{
      "link":"https:\/\/www.screenshottr.us\/v\/27ba44faf78de2d78c7ef7d1f643a66a\/2593bb336d1e8b498dbe5a2888a84e0a.png",
      "id":"9dR",
      "pravius":"https:\/\/pravi.us\/9dR",
      "secret":"VhZws",
      "existed":false
   },
   "url":"https:\/\/pravi.us\/9dR",
   "ScreenShottr":{
      "image":"2593bb336d1e8b498dbe5a2888a84e0a.png",
      "secret":"3d3db9d0c954c45646ddcde5e96fca91",
      "url":"https:\/\/www.screenshottr.us\/v\/27ba44faf78de2d78c7ef7d1f643a66a\/2593bb336d1e8b498dbe5a2888a84e0a.png",
      "key":"27ba44faf78de2d78c7ef7d1f643a66a"
   },
   "ScreenShottrSettings":{
      "encryptedURL":"https:\/\/www.screenshottr.us\/v\/{key}\/{file}",
      "unencryptedURL":"https:\/\/www.screenshottr.us\/{file}",
      "encryptedLandingURL":"https:\/\/www.screenshottr.us\/v\/landing\/{key}\/{file}",
      "unencryptedLandingURL":"https:\/\/www.screenshottr.us\/landing\/{file}"
   }
}
```

It would be very easy for the ScreenShottr-Java application to generate URL's for itself, instead of taking the one provided by the `url` paramater. 

As well as this, the ability to have social sharing within the ScreenShottr applications that allows sharing to Facebook/Twitter/Reddit etc. Not sure how difficult this would be though.

**Comment by Wild1145** [comment]
+1 for this idea :)

**Comment by Fyrsta** [comment]
It shouldn't be too hard to share it around on Facebook/Twitter. Also it wouldn't be too hard to integrate it as a config option in the program. We'll need @JeromSar's response on how feasible this would be in the program, but I don't imagine it to be too hard.

Also, this should be implemented after the current bugs are fixed. It's better to fix the program first rather than adding new features.

**Comment by Wild1145** [comment]
I think what @TheCJGCJG Also suggested is the ability to toggle the /landing and not. This way the /landing would have the social sharing on the servers side and not the application site, though I could be wrong with the way I read it.

**Comment by TheCJGCJG** [comment]
@Wild1145 I suggested adding them both. Both configurable of course.

**Comment by Wild1145** [comment]
@TheCJGCJG I only skim read through to be honest, I did see the stuff about /landing and not much else when I skim read.

**Comment by JeromSar** [comment]
@Wild1145 I will add that in the configuration. Should it be enabled by default?

**Comment by Wild1145** [comment]
@JeromSar I have a feeling that @WickedGamingUK Would have you killed if you did :P But have it easy to change ;)

**Comment by Fyrsta** [comment]
It shouldn't be enabled by default. It takes away from the point of ScreenShottr.

**Comment by TheCJGCJG** [comment]
Have it disabled by default, as @WickedGamingUK it would take away from the point of ScreenShottr.
