### ISSUE TITLE
Selection dialog box does not sync with Cursor

### ISSUE THREAD

**Issue by TheCJGCJG** [ScreenShottr/ScreenShottr-Java#8]
When selecting an area to capture the selection dialog does not meet with the cursor, and is around 30 pixels off. Checked on Mac OS 10.10

[Video](https://www.thecjgcjg.com/downloads/ScreenShottr-Java_Bug_Cursor_Sync.mp4)

**Comment by JeromSar** [comment]
Try again with the latest build I have sent you. @TheCJGCJG

**Comment by TheCJGCJG** [comment]
The latest build has not fixed this.
